"""Unreal asset pipeline environment constants."""

from engine_adapters.ue5.config import (
    DEFAULT_AVATAR_DEST,
    DEFAULT_EFFECT_DEST,
    DEFAULT_ENVIRONMENT_DEST,
    DEFAULT_IMPORT_ROOT,
    DEFAULT_MATERIAL_DEST,
    DEFAULT_MOTION_DEST,
    DEFAULT_PROP_DEST,
    DEFAULT_SCENE_DEST,
    DEFAULT_TEXTURE_DEST,
    DEFAULT_WEAPON_DEST,
    UE_ASSET_TYPE_DEFAULT_DESTS,
)

__all__ = [
    "DEFAULT_AVATAR_DEST",
    "DEFAULT_EFFECT_DEST",
    "DEFAULT_ENVIRONMENT_DEST",
    "DEFAULT_IMPORT_ROOT",
    "DEFAULT_MATERIAL_DEST",
    "DEFAULT_MOTION_DEST",
    "DEFAULT_PROP_DEST",
    "DEFAULT_SCENE_DEST",
    "DEFAULT_TEXTURE_DEST",
    "DEFAULT_WEAPON_DEST",
    "UE_ASSET_TYPE_DEFAULT_DESTS",
]
