"""
models/common/glb_writer.py

Write a binary glTF (`.glb`) from a declarative part spec, with nothing but
the standard library.

This is the write half of `glb_utils.py`, and it exists for the same reason:
the asset path has to work on a CPU-only box with nothing installed. Reaching
for `trimesh` here would make a spec-built crate depend on a numpy/scipy stack
that the spec route exists partly to avoid.

WHY glTF AND NOT A PER-ENGINE FORMAT. Measured from each adapter's own
importer, the formats accepted are:

    UE5        fbx glb gltf obj usd usda usdz
    Blender    abc fbx glb gltf obj ply usd usda usdc usdz
    Unity      fbx glb gltf obj
    three.js   glb gltf

glTF is the intersection, so one writer serves every engine and the spec
route needs no per-engine emitter to be useful on day one.

THE `mesh` KIND. Besides the seven analytic primitives there is a `mesh`
part, which reads a GLB off disk — typically one part generated by a cloud
model. It is fitted into the same `size` box the primitives occupy, so a
generated grip is placed, measured and gated exactly like a box: the
composition does not need to know which parts were authored and which were
generated. What the generator supplies is a shape nobody can state as a
formula; what the spec supplies is where it goes and how big it is, which
a generator cannot be told precisely.

THIS MODULE IS THE SINGLE SOURCE OF TRUTH FOR PART GEOMETRY. The gates in
`operators/gen_3d_object/funcs/code_asset.py` import `rotated_bounds` from
here rather than computing extents their own way. That is deliberate: a gate
that measured the spec differently from the writer would pass a mesh that
was not the mesh being written, which is the same class of silent wrong
answer as an inverted bounding-box convention.

Usage:
    from models.common.glb_writer import write_spec_glb
    write_spec_glb(spec, "model.glb")     # spec: see code_asset.validate_spec
"""
from __future__ import annotations

import json
import math
import struct
from pathlib import Path
from typing import Any, Iterable, Sequence

#: glTF component types used here.
_FLOAT = 5126
_UNSIGNED_INT = 5125

#: glTF primitive mode 4 == TRIANGLES.
_MODE_TRIANGLES = 4

#: Written into `asset.generator`, so a spec-built mesh is identifiable
#: after the fact. `glb_summary` reads this back.
GENERATOR = "3AGameFactory/glb_writer"

Vec3 = tuple[float, float, float]


#: Decoded external meshes, keyed by resolved path. A `mesh` part is read
#: three times per build — bounds, triangle estimate, then the write — and a
#: composition may place the same generated part more than once. Decoding is
#: the one part of this module whose cost is not trivial.
_MESH_CACHE: dict[str, dict[str, Any]] = {}


def load_mesh_asset(source: str) -> dict[str, Any]:
    """Read and cache an external GLB, normalised into a unit box.

    The mesh is centred on its own bounding box and scaled by a *single*
    factor so its longest axis spans 1.0, which puts it in the same frame the
    analytic primitives use: `build_part` then applies `size` to all of them
    identically.

    One factor rather than three, because a generated part arrives with its
    own proportions and stretching each axis to fill the box would destroy
    them — a grip fitted to a 40x110x30 mm box by non-uniform scale is a
    smeared grip, and the smear is the kind of wrongness that reads as a bad
    asset rather than as a bad placement. The consequence is that `size` is
    an upper bound on the two shorter axes rather than an exact extent, and
    `mesh_bounds` reports what the part actually occupies so the gates
    measure the mesh instead of the request.
    """

    resolved = str(Path(source).resolve())
    cached = _MESH_CACHE.get(resolved)
    if cached is not None:
        return cached

    from models.common.glb_utils import read_glb_mesh

    raw = read_glb_mesh(Path(resolved).read_bytes())
    low, high = raw["low"], raw["high"]
    extent = [high[axis] - low[axis] for axis in range(3)]
    longest = max(extent) or 1.0
    centre = [(high[axis] + low[axis]) / 2.0 for axis in range(3)]

    positions = [
        tuple((point[axis] - centre[axis]) / longest for axis in range(3))
        for point in raw["positions"]
    ]
    # Uniform scale leaves normals unchanged in direction, so they carry over
    # as they are. This is the one place a non-uniform fit would also have
    # cost an inverse-transpose pass over every normal.
    entry = {
        "positions": positions,
        "normals": raw["normals"],
        "uvs": raw.get("uvs") or [(0.0, 0.0)] * len(positions),
        "indices": raw["indices"],
        "triangles": raw["triangles"],
        "unit_extent": tuple(value / longest for value in extent),
        "material_runs": raw.get("material_runs") or [],
        "materials": raw.get("materials") or [],
        "has_uvs": bool(raw.get("has_uvs")),
        "source": resolved,
    }
    _MESH_CACHE[resolved] = entry
    return entry


def mesh_unit_extent(source: str) -> Vec3:
    """Fraction of the unit box a normalised external mesh fills, per axis."""
    return load_mesh_asset(source)["unit_extent"]


def effective_size(size: Sequence[float], kind: str) -> Vec3:
    """The scale actually applied to a part, which for a mesh is uniform.

    A `mesh` part is scaled by ``max(size)`` on all three axes, so it keeps
    the proportions it was generated with; the other two numbers are
    discarded. `provenance` warns when they were not all the same, so the
    discarding is visible.

    Both `build_part` and `rotated_bounds` route through here. That is the
    same rule the rest of this module follows and for the same reason: when
    the bound is computed from one scaling rule and the mesh written with
    another, the gates pass an object that is not the object on disk, and
    lathe bounds already demonstrated that failing silently.
    """

    if kind == "mesh":
        uniform = max(float(value) for value in size)
        return (uniform, uniform, uniform)
    return (float(size[0]), float(size[1]), float(size[2]))


#: Default PBR factors for a material a spec did not describe. Mid-grey
#: dielectric: visible under any lighting, obviously placeholder, and never
#: mistaken for authored art.
DEFAULT_MATERIAL: dict[str, Any] = {
    "baseColor": [0.72, 0.72, 0.74, 1.0],
    "metallic": 0.0,
    "roughness": 0.6,
}


# --------------------------------------------------------------------------
# Transform maths, shared with the gates
# --------------------------------------------------------------------------


def euler_matrix(rotation: Sequence[float]) -> tuple[Vec3, Vec3, Vec3]:
    """Row-major rotation matrix for XYZ Euler angles in **degrees**.

    Applied X, then Y, then Z. Stated because the order is not discoverable
    from a result that looks plausible, and a spec authored against one
    convention and evaluated under another produces a mesh that is subtly,
    consistently wrong.
    """

    x, y, z = (math.radians(float(value)) for value in rotation)
    sx, cx = math.sin(x), math.cos(x)
    sy, cy = math.sin(y), math.cos(y)
    sz, cz = math.sin(z), math.cos(z)
    return (
        (cy * cz, cz * sx * sy - cx * sz, cx * cz * sy + sx * sz),
        (cy * sz, cx * cz + sx * sy * sz, -cz * sx + cx * sy * sz),
        (-sy, cy * sx, cx * cy),
    )


def apply_matrix(matrix: tuple[Vec3, Vec3, Vec3], point: Sequence[float]) -> Vec3:
    """Rotate a point or a direction by `matrix`."""
    x, y, z = (float(value) for value in point)
    return (
        matrix[0][0] * x + matrix[0][1] * y + matrix[0][2] * z,
        matrix[1][0] * x + matrix[1][1] * y + matrix[1][2] * z,
        matrix[2][0] * x + matrix[2][1] * y + matrix[2][2] * z,
    )


def rotated_bounds(
    size: Sequence[float],
    at: Sequence[float],
    rotation: Sequence[float],
    profile: Sequence[Sequence[float]] | None = None,
    kind: str = "box",
    source: str | None = None,
) -> tuple[Vec3, Vec3]:
    """Axis-aligned `(low, high)` of a rotated, translated part.

    Every one of the eight corners is transformed and the extremes taken,
    rather than swapping extents for the right-angle cases. Exact for a box
    at any angle, and a true bound for the round primitives, whose surface
    is inside their extent box.

    ``profile``/``kind`` exist because a lathe or extrude profile lives in
    its own coordinates and is *not* confined to the ±``size``/2 box that
    the other kinds are: a lathe whose profile runs -0.185..0.225 in its
    local y is 0.41 m tall whatever ``size`` says, and measuring it as a
    unit box made the scale gate disagree with the written mesh by that
    much. For those two kinds the corners come from the profile itself.

    A ``mesh`` part is the mirror image of that problem: it is fitted into
    ``size`` by a *single* factor to keep its proportions, so it fills the
    box on its longest axis only and reporting ``size`` would over-state the
    two shorter ones. A generated grip requested at 40x110x30 mm but
    naturally 0.42:1:0.38 occupies 46x110x42 mm of that box, and measuring
    it as the full box puts phantom material where there is none — enough to
    make the connectivity gate call a touching part connected when a visible
    gap remains. ``source`` therefore has to be passed in, and the extent
    comes from the decoded mesh.
    """

    matrix = euler_matrix(rotation)
    if kind == "mesh":
        if not source:
            raise ValueError("a mesh part needs `source` to be measured")
        # From the vertices, not from the eight corners of the extent box.
        # For a box the two agree, because a box fills its box; a generated
        # mesh does not, and once rotated the transformed corners of a box it
        # only partly occupies are outside the mesh — a grip raked 8 degrees
        # measured that way is 47 mm tall against an actual 44 mm. The corner
        # trick is an exact bound only for a shape that reaches every corner.
        # Reading vertices is the cost of admitting an arbitrary mesh, and it
        # is paid once because `load_mesh_asset` caches.
        asset = load_mesh_asset(source)
        applied = effective_size(size, kind)
        low = [float("inf")] * 3
        high = [float("-inf")] * 3
        for point in asset["positions"]:
            scaled = (
                point[0] * applied[0],
                point[1] * applied[1],
                point[2] * applied[2],
            )
            turned = apply_matrix(matrix, scaled)
            for axis in range(3):
                value = turned[axis] + float(at[axis])
                low[axis] = min(low[axis], value)
                high[axis] = max(high[axis], value)
        return (low[0], low[1], low[2]), (high[0], high[1], high[2])

    if profile and kind in ("lathe", "extrude"):
        points: list[tuple[float, float, float]] = []
        if kind == "lathe":
            # (radius, height) revolved about y: the extreme ring is at the
            # max radius, swept the full circle.
            max_radius = max(abs(float(radius)) for radius, _h in profile)
            for _radius, height in profile:
                points.append((max_radius, float(height), max_radius))
                points.append((max_radius, float(height), -max_radius))
                points.append((-max_radius, float(height), max_radius))
                points.append((-max_radius, float(height), -max_radius))
        else:
            # (x, y) outline pushed along z by size[2].
            for x, y in profile:
                points.append((float(x), float(y), size[2] / 2.0))
                points.append((float(x), float(y), -size[2] / 2.0))
        low = [float("inf")] * 3
        high = [float("-inf")] * 3
        for point in points:
            corner = apply_matrix(matrix, point)
            for axis in range(3):
                value = corner[axis] + float(at[axis])
                low[axis] = min(low[axis], value)
                high[axis] = max(high[axis], value)
        return (low[0], low[1], low[2]), (high[0], high[1], high[2])

    half = [float(value) / 2.0 for value in size]
    low = [float("inf")] * 3
    high = [float("-inf")] * 3
    for sx in (-1.0, 1.0):
        for sy in (-1.0, 1.0):
            for sz in (-1.0, 1.0):
                corner = apply_matrix(
                    matrix, (sx * half[0], sy * half[1], sz * half[2])
                )
                for axis in range(3):
                    value = corner[axis] + float(at[axis])
                    low[axis] = min(low[axis], value)
                    high[axis] = max(high[axis], value)
    return (low[0], low[1], low[2]), (high[0], high[1], high[2])


# --------------------------------------------------------------------------
# Primitive meshes
#
# Each returns (positions, normals, indices) in a unit-sized, origin-centred
# frame, which `build_part` then scales, rotates and translates. Normals are
# per-vertex and generated with the geometry rather than derived afterwards:
# a flat-shaded box needs four vertices per face, and recovering that from a
# shared-vertex mesh means guessing where the creases were.
# --------------------------------------------------------------------------


def _box(chamfer: float = 0.0) -> tuple[list[Vec3], list[Vec3], list[int]]:
    """A unit box, optionally with its twelve edges cut back.

    ``chamfer`` is a fraction of the half-extent, 0..0.5. A real moulded or
    machined part has no perfectly sharp edge; the sharp edge is what makes
    a box read as a toy brick, because it catches the light as one hard line
    instead of a highlight with width. Cutting the edges back gives each one
    a narrow face that takes its own specular, which is most of the
    difference between "primitive" and "modelled" at no texture cost.

    The chamfered solid is strictly *inside* the unit box — every vertex
    stays within ±0.5 — so ``rotated_bounds`` remains a true bound and the
    scale and connectivity gates need no knowledge of this field.
    """

    if chamfer <= 0.0:
        return _sharp_box()

    cut = min(max(float(chamfer), 0.0), 0.5)
    inner = 0.5 - cut
    positions: list[Vec3] = []
    normals: list[Vec3] = []
    indices: list[int] = []

    def face(normal: Vec3, corners: Sequence[Vec3]) -> None:
        """Emit one convex planar polygon facing ``normal``.

        The winding is not asserted by hand but derived: the cross product of
        the first two edges gives the polygon's geometric facing, and if that
        opposes the intended outward normal the order is reversed. Choosing
        signs by inspection across 6 faces, 12 bevels and 8 corners is where
        a hand-wound chamfer goes wrong, and an inward-facing triangle is
        invisible from outside — so it survives a screenshot and fails in an
        engine that culls backfaces.
        """

        edge1 = tuple(corners[1][i] - corners[0][i] for i in range(3))
        edge2 = tuple(corners[2][i] - corners[1][i] for i in range(3))
        cross = (
            edge1[1] * edge2[2] - edge1[2] * edge2[1],
            edge1[2] * edge2[0] - edge1[0] * edge2[2],
            edge1[0] * edge2[1] - edge1[1] * edge2[0],
        )
        ordered = list(corners)
        if sum(cross[i] * normal[i] for i in range(3)) < 0.0:
            ordered.reverse()

        length = math.sqrt(sum(value * value for value in normal)) or 1.0
        unit = (normal[0] / length, normal[1] / length, normal[2] / length)
        base = len(positions)
        positions.extend(tuple(float(value) for value in point) for point in ordered)  # type: ignore[misc]
        normals.extend([unit] * len(ordered))
        for offset in range(1, len(ordered) - 1):
            indices.extend([base, base + offset, base + offset + 1])

    def at(axis: int, value: float, u: int, uv: float, v: int, vv: float) -> Vec3:
        point = [0.0, 0.0, 0.0]
        point[axis], point[u], point[v] = value, uv, vv
        return (point[0], point[1], point[2])

    # Six shrunken faces.
    for axis in range(3):
        u, v = (axis + 1) % 3, (axis + 2) % 3
        for sign in (1.0, -1.0):
            normal = [0.0, 0.0, 0.0]
            normal[axis] = sign
            face(
                (normal[0], normal[1], normal[2]),
                [
                    at(axis, sign * 0.5, u, du * inner, v, dv * inner)
                    for du, dv in ((-1.0, -1.0), (1.0, -1.0), (1.0, 1.0), (-1.0, 1.0))
                ],
            )

    # Twelve edge bevels: one per pair of adjacent faces, running along `axis`.
    for axis in range(3):
        u, v = (axis + 1) % 3, (axis + 2) % 3
        for su in (1.0, -1.0):
            for sv in (1.0, -1.0):
                normal = [0.0, 0.0, 0.0]
                normal[u], normal[v] = su, sv
                face(
                    (normal[0], normal[1], normal[2]),
                    [
                        at(axis, -inner, u, su * 0.5, v, sv * inner),
                        at(axis, -inner, u, su * inner, v, sv * 0.5),
                        at(axis, inner, u, su * inner, v, sv * 0.5),
                        at(axis, inner, u, su * 0.5, v, sv * inner),
                    ],
                )

    # Eight corner triangles, closing what the bevels leave open.
    for sx in (1.0, -1.0):
        for sy in (1.0, -1.0):
            for sz in (1.0, -1.0):
                face(
                    (sx, sy, sz),
                    [
                        (sx * 0.5, sy * inner, sz * inner),
                        (sx * inner, sy * 0.5, sz * inner),
                        (sx * inner, sy * inner, sz * 0.5),
                    ],
                )

    return positions, normals, indices


def _sharp_box() -> tuple[list[Vec3], list[Vec3], list[int]]:
    faces = (
        ((0, 0, 1), ((-0.5, -0.5, 0.5), (0.5, -0.5, 0.5), (0.5, 0.5, 0.5), (-0.5, 0.5, 0.5))),
        ((0, 0, -1), ((0.5, -0.5, -0.5), (-0.5, -0.5, -0.5), (-0.5, 0.5, -0.5), (0.5, 0.5, -0.5))),
        ((1, 0, 0), ((0.5, -0.5, 0.5), (0.5, -0.5, -0.5), (0.5, 0.5, -0.5), (0.5, 0.5, 0.5))),
        ((-1, 0, 0), ((-0.5, -0.5, -0.5), (-0.5, -0.5, 0.5), (-0.5, 0.5, 0.5), (-0.5, 0.5, -0.5))),
        ((0, 1, 0), ((-0.5, 0.5, 0.5), (0.5, 0.5, 0.5), (0.5, 0.5, -0.5), (-0.5, 0.5, -0.5))),
        ((0, -1, 0), ((-0.5, -0.5, -0.5), (0.5, -0.5, -0.5), (0.5, -0.5, 0.5), (-0.5, -0.5, 0.5))),
    )
    positions: list[Vec3] = []
    normals: list[Vec3] = []
    indices: list[int] = []
    for normal, corners in faces:
        base = len(positions)
        positions.extend(corners)
        normals.extend([tuple(float(v) for v in normal)] * 4)  # type: ignore[arg-type]
        indices.extend([base, base + 1, base + 2, base, base + 2, base + 3])
    return positions, normals, indices


def _cylinder(segments: int) -> tuple[list[Vec3], list[Vec3], list[int]]:
    positions: list[Vec3] = []
    normals: list[Vec3] = []
    indices: list[int] = []

    # Side wall: its own vertices, so the wall's outward normals do not get
    # averaged with the caps' and round off the rim.
    for step in range(segments + 1):
        angle = 2.0 * math.pi * step / segments
        cos_a, sin_a = math.cos(angle), math.sin(angle)
        positions.append((0.5 * cos_a, -0.5, 0.5 * sin_a))
        positions.append((0.5 * cos_a, 0.5, 0.5 * sin_a))
        normals.extend([(cos_a, 0.0, sin_a), (cos_a, 0.0, sin_a)])
    for step in range(segments):
        base = step * 2
        indices.extend(
            [base, base + 3, base + 2, base, base + 1, base + 3]
        )

    for sign, normal in ((0.5, (0.0, 1.0, 0.0)), (-0.5, (0.0, -1.0, 0.0))):
        centre = len(positions)
        positions.append((0.0, sign, 0.0))
        normals.append(normal)
        for step in range(segments + 1):
            angle = 2.0 * math.pi * step / segments
            positions.append((0.5 * math.cos(angle), sign, 0.5 * math.sin(angle)))
            normals.append(normal)
        for step in range(segments):
            first, second = centre + 1 + step, centre + 2 + step
            indices.extend(
                [centre, second, first] if sign > 0 else [centre, first, second]
            )
    return positions, normals, indices


def _cone(segments: int) -> tuple[list[Vec3], list[Vec3], list[int]]:
    positions: list[Vec3] = [(0.0, 0.5, 0.0)]
    normals: list[Vec3] = [(0.0, 1.0, 0.0)]
    indices: list[int] = []
    for step in range(segments + 1):
        angle = 2.0 * math.pi * step / segments
        cos_a, sin_a = math.cos(angle), math.sin(angle)
        positions.append((0.5 * cos_a, -0.5, 0.5 * sin_a))
        # Slant normal for a unit cone: the side rises one unit over a half-
        # unit radius, so the vertical component is 0.5 before normalising.
        length = math.sqrt(1.0 + 0.25)
        normals.append((cos_a / length, 0.5 / length, sin_a / length))
    for step in range(segments):
        indices.extend([0, step + 2, step + 1])

    centre = len(positions)
    positions.append((0.0, -0.5, 0.0))
    normals.append((0.0, -1.0, 0.0))
    for step in range(segments + 1):
        angle = 2.0 * math.pi * step / segments
        positions.append((0.5 * math.cos(angle), -0.5, 0.5 * math.sin(angle)))
        normals.append((0.0, -1.0, 0.0))
    for step in range(segments):
        indices.extend([centre, centre + 1 + step, centre + 2 + step])
    return positions, normals, indices


def _sphere(segments: int) -> tuple[list[Vec3], list[Vec3], list[int]]:
    rings = max(3, segments // 2)
    positions: list[Vec3] = []
    normals: list[Vec3] = []
    indices: list[int] = []
    for ring in range(rings + 1):
        phi = math.pi * ring / rings
        for step in range(segments + 1):
            theta = 2.0 * math.pi * step / segments
            nx = math.sin(phi) * math.cos(theta)
            ny = math.cos(phi)
            nz = math.sin(phi) * math.sin(theta)
            positions.append((0.5 * nx, 0.5 * ny, 0.5 * nz))
            normals.append((nx, ny, nz))
    stride = segments + 1
    for ring in range(rings):
        for step in range(segments):
            a = ring * stride + step
            b = a + stride
            indices.extend([a, b + 1, b, a, a + 1, b + 1])
    return positions, normals, indices


def _torus(segments: int, tube_ratio: float = 0.3) -> tuple[list[Vec3], list[Vec3], list[int]]:
    tube_segments = max(3, segments // 2)
    ring_radius = 0.5 - 0.5 * tube_ratio
    tube_radius = 0.5 * tube_ratio
    positions: list[Vec3] = []
    normals: list[Vec3] = []
    indices: list[int] = []
    for ring in range(segments + 1):
        theta = 2.0 * math.pi * ring / segments
        cos_t, sin_t = math.cos(theta), math.sin(theta)
        for step in range(tube_segments + 1):
            phi = 2.0 * math.pi * step / tube_segments
            cos_p, sin_p = math.cos(phi), math.sin(phi)
            positions.append((
                (ring_radius + tube_radius * cos_p) * cos_t,
                tube_radius * sin_p,
                (ring_radius + tube_radius * cos_p) * sin_t,
            ))
            normals.append((cos_p * cos_t, sin_p, cos_p * sin_t))
    stride = tube_segments + 1
    for ring in range(segments):
        for step in range(tube_segments):
            a = ring * stride + step
            b = a + stride
            indices.extend([a, b + 1, b, a, a + 1, b + 1])
    return positions, normals, indices


def _lathe(profile: Sequence[Sequence[float]], segments: int
           ) -> tuple[list[Vec3], list[Vec3], list[int]]:
    """Revolve a `(radius, height)` profile about Y.

    Carries the shapes — bottles, blades, mouldings, turned legs — that
    would otherwise each need a bespoke primitive. Profile coordinates are
    in the same unit frame as everything else and are scaled by `size`.
    """

    points = [(float(r), float(h)) for r, h in profile]
    if len(points) < 2:
        raise ValueError("a lathe profile needs at least two points")

    # Ordered low to high, for the same reason the extrude outline is ordered
    # counter-clockwise: the winding below depends on the direction of travel,
    # and a profile written from the muzzle back is as natural as one written
    # from the breech forward. Normalising here means there is no wrong way to
    # enter a profile, rather than a requirement to remember.
    if points[-1][1] < points[0][1]:
        points.reverse()

    positions: list[Vec3] = []
    normals: list[Vec3] = []
    indices: list[int] = []
    for step in range(segments + 1):
        angle = 2.0 * math.pi * step / segments
        cos_a, sin_a = math.cos(angle), math.sin(angle)
        for index, (radius, height) in enumerate(points):
            positions.append((radius * cos_a, height, radius * sin_a))
            # Profile tangent, rotated a quarter turn into an outward normal.
            previous = points[max(0, index - 1)]
            following = points[min(len(points) - 1, index + 1)]
            dr = following[0] - previous[0]
            dh = following[1] - previous[1]
            length = math.hypot(dr, dh) or 1.0
            nr, ny = dh / length, -dr / length
            normals.append((nr * cos_a, ny, nr * sin_a))
    stride = len(points)
    for step in range(segments):
        for index in range(stride - 1):
            a = step * stride + index
            b = a + stride
            # Wound so the face points away from the axis of revolution, which
            # is what the per-vertex normals above already claim. The first
            # version had these reversed: every lathed part was inside-out,
            # with a signed volume of -0.784 where a unit cylinder is +0.785.
            # Nothing caught it, because a viewer that does not cull backfaces
            # shades an inverted solid identically — the defect only appears
            # once it is in an engine, which is the far side of the handoff.
            indices.extend([a, b + 1, b, a, a + 1, b + 1])
    return positions, normals, indices


def _extrude(profile: Sequence[Sequence[float]], depth: float = 1.0
             ) -> tuple[list[Vec3], list[Vec3], list[int]]:
    """Extrude a closed 2D `(x, y)` outline along Z, with flat caps.

    The outline is reordered counter-clockwise first. Winding the walls and
    caps correctly depends on knowing which way the outline runs, and an
    outline traced clockwise is exactly as natural to write as one traced
    the other way — the rifle's stock was traced clockwise and came out
    inside-out. Deriving the direction from the signed area rather than
    documenting a requirement removes the whole class of mistake: there is
    no wrong way to enter an outline.
    """

    outline = [(float(x), float(y)) for x, y in profile]
    if len(outline) < 3:
        raise ValueError("an extrude profile needs at least three points")

    # Shoelace formula. Negative means the outline runs clockwise.
    area = 0.0
    for index in range(len(outline)):
        x0, y0 = outline[index]
        x1, y1 = outline[(index + 1) % len(outline)]
        area += x0 * y1 - x1 * y0
    if area < 0.0:
        outline.reverse()

    half = depth / 2.0
    positions: list[Vec3] = []
    normals: list[Vec3] = []
    indices: list[int] = []

    count = len(outline)
    for index in range(count):
        x0, y0 = outline[index]
        x1, y1 = outline[(index + 1) % count]
        edge_x, edge_y = x1 - x0, y1 - y0
        length = math.hypot(edge_x, edge_y) or 1.0
        normal = (edge_y / length, -edge_x / length, 0.0)
        base = len(positions)
        positions.extend([
            (x0, y0, -half), (x1, y1, -half), (x1, y1, half), (x0, y0, half),
        ])
        normals.extend([normal] * 4)
        indices.extend([base, base + 1, base + 2, base, base + 2, base + 3])

    # Fan-triangulated caps: correct for the convex outlines a hard-surface
    # spec uses, and a concave one shows up immediately in the review sheet
    # rather than silently producing a filled notch.
    for sign, normal in ((half, (0.0, 0.0, 1.0)), (-half, (0.0, 0.0, -1.0))):
        base = len(positions)
        for x, y in outline:
            positions.append((x, y, sign))
            normals.append(normal)
        for index in range(1, count - 1):
            triangle = (base, base + index, base + index + 1)
            indices.extend(triangle if sign > 0 else tuple(reversed(triangle)))
    return positions, normals, indices


def build_part(part: dict[str, Any]) -> tuple[list[Vec3], list[Vec3], list[int]]:
    """Evaluate one spec part into world-space positions, normals and indices."""

    kind = part["kind"]
    segments = max(3, int(part.get("segments") or 16))
    profile = part.get("profile")

    if kind == "box":
        positions, normals, indices = _box(float(part.get("chamfer") or 0.0))
    elif kind == "cylinder":
        positions, normals, indices = _cylinder(segments)
    elif kind == "cone":
        positions, normals, indices = _cone(segments)
    elif kind == "sphere":
        positions, normals, indices = _sphere(segments)
    elif kind == "torus":
        positions, normals, indices = _torus(segments)
    elif kind == "lathe":
        positions, normals, indices = _lathe(profile or ((0.5, -0.5), (0.5, 0.5)), segments)
    elif kind == "extrude":
        positions, normals, indices = _extrude(
            profile or ((-0.5, -0.5), (0.5, -0.5), (0.5, 0.5), (-0.5, 0.5))
        )
    elif kind == "mesh":
        source = part.get("source")
        if not source:
            raise ValueError(f"{part.get('id')}: a mesh part needs a `source` path")
        asset = load_mesh_asset(str(source))
        positions = list(asset["positions"])
        normals = list(asset["normals"])
        indices = list(asset["indices"])
    else:
        raise ValueError(f"unknown primitive kind {kind!r}")

    size = effective_size(part["size"], kind)
    at = part["at"]
    matrix = euler_matrix(part.get("rotation") or (0.0, 0.0, 0.0))

    placed: list[Vec3] = []
    for x, y, z in positions:
        scaled = (x * size[0], y * size[1], z * size[2])
        rx, ry, rz = apply_matrix(matrix, scaled)
        placed.append((rx + at[0], ry + at[1], rz + at[2]))

    # Normals transform by the inverse transpose, which for a non-uniform
    # scale is *not* the same matrix — using the forward one tilts every
    # normal on any part that is not scaled equally in all three axes, and
    # the result is lighting that looks like a modelling error.
    inverse_scale = tuple(1.0 / value if value else 0.0 for value in size)
    turned: list[Vec3] = []
    for nx, ny, nz in normals:
        sx = nx * inverse_scale[0]
        sy = ny * inverse_scale[1]
        sz = nz * inverse_scale[2]
        rx, ry, rz = apply_matrix(matrix, (sx, sy, sz))
        length = math.sqrt(rx * rx + ry * ry + rz * rz) or 1.0
        turned.append((rx / length, ry / length, rz / length))

    return placed, turned, indices


# --------------------------------------------------------------------------
# GLB assembly
# --------------------------------------------------------------------------


def _pad(data: bytearray, alignment: int = 4, fill: int = 0) -> None:
    while len(data) % alignment:
        data.append(fill)


def _fetched_material(
    fetched: dict[str, Any],
    source_index: int | None,
    part_id: str,
    materials: list[dict[str, Any]],
    material_index: dict[str, int],
    textures: list[dict[str, Any]],
    images: list[dict[str, Any]],
    samplers: list[dict[str, Any]],
    add_view: Any,
) -> int:
    """Re-emit one of a fetched part's materials, image and all.

    Keyed on the source path plus the material's index within it, so a part
    placed twice — two front wheels, four identical bolts — shares one copy
    of a texture that may be several megabytes. Without that the file grows
    by the size of the atlas per instance, and a GLB large enough to stall an
    import is a delivery failure rather than a modelling one.
    """

    key = f"@{fetched['source']}#{source_index}"
    if key in material_index:
        return material_index[key]

    described = (
        fetched["materials"][source_index]
        if source_index is not None and source_index < len(fetched["materials"])
        else {}
    )
    colour = list(described.get("baseColor") or [1.0, 1.0, 1.0, 1.0])
    if len(colour) == 3:
        colour.append(1.0)

    material: dict[str, Any] = {
        "name": f"{part_id}:{described.get('name') or source_index or 0}",
        "pbrMetallicRoughness": {
            "baseColorFactor": [float(value) for value in colour],
            "metallicFactor": float(described.get("metallic", 0.0)),
            "roughnessFactor": float(described.get("roughness", 0.6)),
        },
        "doubleSided": False,
    }

    if described.get("image"):
        if not samplers:
            # Linear filtering with mipmaps and repeating wrap: the defaults a
            # game engine would apply anyway, stated so the file does not
            # depend on the importer choosing them.
            samplers.append({
                "magFilter": 9729,            # LINEAR
                "minFilter": 9987,            # LINEAR_MIPMAP_LINEAR
                "wrapS": 10497, "wrapT": 10497,
            })
        image_view = add_view(described["image"])
        images.append({
            "bufferView": image_view,
            "mimeType": described.get("mimeType") or "image/png",
            "name": f"{part_id}-basecolour",
        })
        textures.append({"sampler": 0, "source": len(images) - 1})
        material["pbrMetallicRoughness"]["baseColorTexture"] = {
            "index": len(textures) - 1
        }

    materials.append(material)
    material_index[key] = len(materials) - 1
    return material_index[key]


def write_spec_glb(spec: dict[str, Any], out_path: str | Path) -> str:
    """Write `spec` as a `.glb` and return the path.

    One glTF mesh per spec part, each as its own node **keeping the part's
    id as the node name**. That is the property a generated mesh cannot
    offer: a wheel arrives as a node called `wheel-fl`, so gameplay can spin
    it after import instead of the whole vehicle being one fused body.
    """

    parts = spec["parts"]
    if not parts:
        raise ValueError("a spec needs at least one part")

    materials_in = spec.get("materials") or {}
    material_index: dict[str, int] = {}
    materials: list[dict[str, Any]] = []
    textures: list[dict[str, Any]] = []
    images: list[dict[str, Any]] = []
    samplers: list[dict[str, Any]] = []

    buffer = bytearray()
    views: list[dict[str, Any]] = []
    accessors: list[dict[str, Any]] = []
    meshes: list[dict[str, Any]] = []
    nodes: list[dict[str, Any]] = []

    def add_view(payload: bytes, target: int | None = None) -> int:
        _pad(buffer)                     # accessor offsets must stay aligned
        offset = len(buffer)
        buffer.extend(payload)
        view: dict[str, Any] = {
            "buffer": 0,
            "byteOffset": offset,
            "byteLength": len(payload),
        }
        if target is not None:
            view["target"] = target
        views.append(view)
        return len(views) - 1

    for part in parts:
        positions, normals, indices = build_part(part)

        # A generated part brings its own UVs and textures, and they are the
        # reason it was fetched: the stippling on a grip and the panel creases
        # on a car shell live in the texture, not the mesh. A primitive has no
        # UVs — writing arbitrary ones would put a stretched fragment of
        # somebody else's atlas on a rail.
        fetched = (
            load_mesh_asset(str(part["source"]))
            if part["kind"] == "mesh" and part.get("source") else None
        )
        textured = bool(fetched and fetched["has_uvs"] and fetched["materials"])

        position_view = add_view(
            b"".join(struct.pack("<3f", *point) for point in positions), 34962
        )
        normal_view = add_view(
            b"".join(struct.pack("<3f", *vector) for vector in normals), 34962
        )
        index_view = add_view(
            b"".join(struct.pack("<I", value) for value in indices), 34963
        )

        low = [min(point[axis] for point in positions) for axis in range(3)]
        high = [max(point[axis] for point in positions) for axis in range(3)]

        # POSITION requires min/max: a viewer uses them to frame the scene,
        # and a validator rejects the file without them.
        accessors.append({
            "bufferView": position_view,
            "componentType": _FLOAT,
            "count": len(positions),
            "type": "VEC3",
            "min": [round(value, 6) for value in low],
            "max": [round(value, 6) for value in high],
        })
        accessors.append({
            "bufferView": normal_view,
            "componentType": _FLOAT,
            "count": len(normals),
            "type": "VEC3",
        })
        accessors.append({
            "bufferView": index_view,
            "componentType": _UNSIGNED_INT,
            "count": len(indices),
            "type": "SCALAR",
        })
        position_accessor = len(accessors) - 3
        normal_accessor = len(accessors) - 2
        index_accessor = len(accessors) - 1

        attributes = {
            "POSITION": position_accessor,
            "NORMAL": normal_accessor,
        }
        if textured:
            uv_view = add_view(
                b"".join(struct.pack("<2f", *uv) for uv in fetched["uvs"]), 34962
            )
            accessors.append({
                "bufferView": uv_view,
                "componentType": _FLOAT,
                "count": len(fetched["uvs"]),
                "type": "VEC2",
            })
            attributes["TEXCOORD_0"] = len(accessors) - 1

        name = str(part.get("material") or "default")
        if name not in material_index:
            described = {**DEFAULT_MATERIAL, **(materials_in.get(name) or {})}
            colour = list(described.get("baseColor", DEFAULT_MATERIAL["baseColor"]))
            if len(colour) == 3:
                colour.append(1.0)
            materials.append({
                "name": name,
                "pbrMetallicRoughness": {
                    "baseColorFactor": [float(value) for value in colour],
                    "metallicFactor": float(described.get("metallic", 0.0)),
                    "roughnessFactor": float(described.get("roughness", 0.6)),
                },
                "doubleSided": bool(described.get("doubleSided", False)),
            })
            material_index[name] = len(materials) - 1

        if not textured:
            primitives = [{
                "attributes": attributes,
                "indices": index_accessor,
                "material": material_index[name],
                "mode": _MODE_TRIANGLES,
            }]
        else:
            # One primitive per material run. A fetched part may use several
            # materials over one vertex buffer — a car body has paint, glass
            # and a carbon insert — and collapsing them to one would put the
            # paint texture on the canopy. The runs come from the source file's
            # own primitive boundaries, so the split is the one it shipped with
            # rather than one guessed here.
            primitives = []
            for run in fetched["material_runs"]:
                if not run["count"]:
                    continue
                run_view = add_view(
                    b"".join(
                        struct.pack("<I", value)
                        for value in indices[run["start"]:run["start"] + run["count"]]
                    ),
                    34963,
                )
                accessors.append({
                    "bufferView": run_view,
                    "componentType": _UNSIGNED_INT,
                    "count": run["count"],
                    "type": "SCALAR",
                })
                primitives.append({
                    "attributes": attributes,
                    "indices": len(accessors) - 1,
                    "material": _fetched_material(
                        fetched, run["material"], part["id"],
                        materials, material_index, textures, images, samplers,
                        add_view,
                    ),
                    "mode": _MODE_TRIANGLES,
                })
            if not primitives:            # no usable runs; fall back to flat
                primitives = [{
                    "attributes": {
                        "POSITION": position_accessor,
                        "NORMAL": normal_accessor,
                    },
                    "indices": index_accessor,
                    "material": material_index[name],
                    "mode": _MODE_TRIANGLES,
                }]

        meshes.append({"name": part["id"], "primitives": primitives})
        nodes.append({"name": part["id"], "mesh": len(meshes) - 1})

    document: dict[str, Any] = {
        "asset": {
            "version": "2.0",
            "generator": GENERATOR,
        },
        "scene": 0,
        "scenes": [{
            "name": spec.get("subject") or "asset",
            "nodes": list(range(len(nodes))),
        }],
        "nodes": nodes,
        "meshes": meshes,
        "materials": materials,
        "accessors": accessors,
        "bufferViews": views,
        "buffers": [{"byteLength": len(buffer)}],
    }
    # Only present when something is textured. An empty `images` array is
    # legal but makes a file look as though a texture failed to write.
    if textures:
        document["textures"] = textures
        document["images"] = images
        document["samplers"] = samplers
    # The spec is kept inside the file it produced. A GLB whose spec has
    # been lost cannot be corrected by editing a number, which is most of
    # the reason to build assets this way.
    document["extras"] = {
        "gamefactory3a": {
            "spec": spec,
            "forwardAxis": spec.get("forward"),
            "heightMetres": spec.get("height_metres"),
            "units": spec.get("units"),
            # Which parts were generated rather than derived, recorded in the
            # file itself. After export the two are indistinguishable — same
            # triangles, same node naming — so without this there is no way to
            # tell later which parts can be adjusted by editing a number and
            # which would have to be regenerated.
            "generatedParts": {
                part["id"]: part["source"]
                for part in spec["parts"]
                if part.get("kind") == "mesh" and part.get("source")
            },
        }
    }

    json_chunk = bytearray(json.dumps(document, separators=(",", ":")).encode("utf-8"))
    _pad(json_chunk, 4, ord(" "))        # JSON pads with spaces, BIN with zeros
    binary_chunk = bytearray(buffer)
    _pad(binary_chunk, 4, 0)

    total = 12 + 8 + len(json_chunk) + 8 + len(binary_chunk)
    out = bytearray()
    out.extend(struct.pack("<4sII", b"glTF", 2, total))
    out.extend(struct.pack("<I4s", len(json_chunk), b"JSON"))
    out.extend(json_chunk)
    out.extend(struct.pack("<I4s", len(binary_chunk), b"BIN\x00"))
    out.extend(binary_chunk)

    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(bytes(out))
    return str(path)
