name: aaagf-retarget-bpy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - xorg-libsm
  - xorg-libxext
  - xorg-libxrender
  - pip:
      - bpy==4.2.0
      - numpy<2
      - trimesh>=4.2
